apiVersion: v1
kind: Secret
metadata:
  name: mywebapp-secrets
  namespace: mywebapp 
type: Opaque
data:
  mywebapp-sshfs-pass: UGFzc3dvcmQxIVBhc3N3b3JkMSEK 
  my-webapp-sshfs-authorized-key: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFEU2pmSHZtaFpUVEptVmR5VnBNYmIwRmVLbCsvTVRTTVUreWxidzl0ZWc2VUY3Y2ZFeGRHeUR3QWp6eWxrS2poeWI0Y1phMXNkZVo5eXZqUjFpRlMvWEovUldLa2lvT0djMHpQZXdSSyttaUtKUzd5cFNGYkJpc1MweFFzTkoxY041bUxvSENQZVZnZmRQUm1CV3ptcklLYmFpdmExWmYxdlJrTno3M3Q0a1h5b0RnL25RUGlaMWQrK2Zwb1owcmhadWsybVhZNFdSVisrMS9VdVQ0UVNDbDRRZ1dpQjNLaFpGeWRzOEtXMFhkdEZZWlZIUWpObGphbVJPcHpTdGF2N2tPeGdVTCs5UUJSRmJMZW5ZNnZ3QkluMFFGRDQyQURGcG8ybkRiVk1YU3NPQjk3NEVXSXlaR2E4R2R4d2VUZ0p1cXFycHU0VjlPc3B6UjZOYlBBU0QgZ3lvdW5nQEdvcmRvbnMtTUJQCg== 

