---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-repo
  namespace: mywebapp
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/webapp-repo
---

